# Generated by Django 4.0.3 on 2022-04-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreGenero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('idSerie', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreOriginal', models.CharField(max_length=100)),
                ('nombreTraduccion', models.CharField(max_length=100)),
                ('fechaDeEstreno', models.DateField()),
                ('guionista', models.CharField(max_length=100)),
                ('temporadasEmitidas', models.IntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreOriginal', models.CharField(max_length=100)),
                ('nombreTraduccion', models.CharField(max_length=100)),
                ('fechaDeEstreno', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('guionista', models.CharField(max_length=100)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.genero')),
            ],
        ),
    ]
