# Generated by Django 4.0.3 on 2022-04-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_pelicula_sinopsis_serie_sinopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idVideo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreOriginal', models.CharField(max_length=100)),
                ('nombreTraduccion', models.CharField(max_length=100)),
                ('fechaDeEstreno', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('creador', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('sinopsis', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
